version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: contentDB
    networks:
      - local_network

  postgres:
    #    use to run on linux
    #    image: postgis/postgis:16-3.5-alpine
    image: postgres:16
    #    remove it to run on Windows
    platform: linux/arm64
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: siteparser
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local_network

volumes:
  postgres_data:
  mongo-data:

networks:
  local_network:
    driver: bridge
